# Gatus Configuration for AdGuard Home HA Integration
# This configuration demonstrates endpoint monitoring that will be polled by AdGuard Home HA
# AdGuard Home HA will poll the Gatus API directly, no webhooks needed

# Endpoints to monitor
# IMPORTANT: Use groups to organize endpoints. AdGuard Home HA will reference them using the
# full key format: "<GROUP_NAME>_<ENDPOINT_NAME>"
endpoints:
  # Production web service monitoring
  - name: "primary-web-check"  
    group: "production"          # Key: production_primary-web-check
    url: "http://192.168.1.100:8080/health"
    method: GET
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    # No alerts needed - AdGuard Home HA polls the status directly

  # Secondary web service for redundancy  
  - name: "secondary-web-check"
    group: "production"          # Key: production_secondary-web-check
    url: "http://192.168.1.100:8080/health"  # Same service, different monitor
    method: GET
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    # No alerts needed - AdGuard Home HA polls the status directly

  # Backup service monitoring
  - name: "backup-web-check"
    group: "production"          # Key: production_backup-web-check  
    url: "http://192.168.1.101:8080/health"
    method: GET
    interval: 30s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 2000"
    # No alerts needed - AdGuard Home HA polls the status directly

  # API service with JSON response validation
  - name: "api-service-check"
    group: "production"          # Key: production_api-service-check
    url: "https://api.example.com/health"
    method: GET
    interval: 45s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 3000"
      - "[BODY].status == 'UP'"
    # No alerts needed - AdGuard Home HA polls the status directly

  # External website monitoring
  - name: "external-web-check"
    group: "external"            # Key: external_external-web-check
    url: "https://www.example.com"
    method: GET
    interval: 60s
    conditions:
      - "[STATUS] == 200"
      - "[RESPONSE_TIME] < 5000"
      - "len([BODY]) > 1000"
    # No alerts needed - AdGuard Home HA polls the status directly

# Configuration Tips:
# 1. Use groups to organize endpoints logically (production, staging, external, etc.)
# 2. AdGuard Home HA references endpoints using full keys: "<GROUP_NAME>_<ENDPOINT_NAME>"
# 3. Special characters (space, /, _, ,, ., #) in groups/names are replaced with "-"
# 4. Set intervals based on your SLA requirements (30s for critical services)
# 5. Use multiple endpoints per service for redundancy
# 6. Example: name="web-check" + group="prod" = key="prod_web-check"
